### ISSUE TITLE
Skeleton stands on "air" and blocks the way

### ISSUE THREAD

**Issue by Randalf98** [tizian/Cendric2#48]
![skeletonblocking](https://user-images.githubusercontent.com/12735077/32667731-d01340b4-c63b-11e7-9733-7f5faee026b4.PNG)

Skeleton is standing in the air and blocking passage.
Only possibility is using reflection enhancement on spell.

**Comment by Randalf98** [comment]
It's possible to stand on the block even if other blocks are on it,

**Comment by OGwold** [comment]
I found that as well. It's easy to get past since wind damages the skeleton, but it takes way to long time for it to be kept that way.

**Comment by Randalf98** [comment]
As far as i see it's a flaw from some block that you can stand on them no matter what is on them(another block, spikes)

**Comment by Ironbell** [comment]
The blocks should push the skeleton, right?

**Comment by Randalf98** [comment]
That would be a good solution.

**Comment by Ironbell** [comment]
Ok the problem here was that those wind blocks were only 48 pixel wide (instead of 50), so the skeleton was standing on a 1px ledge which is ok. The blocks are now also 50 pixels wide. I dunno anymore what I thought when I did this. Maybe I needed it to push blocks down a 1 tile wide pit. This change may break other stuff now. ^^'

**Comment by Ironbell** [comment]
Yes, can't solve the forgotten passage puzzle right now. I'd rather remove the skeleton from this location.
